server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location /gpx-viewer/ {
    root /usr/share/nginx/html;  # 假設 dist 被複製到這裡
    index index.html;
    try_files $uri $uri/ /gpx-viewer/index.html;
  }
}
